config/routes.rb
Rails.application.routes.draw do
  resources :boxes do
    resources :data, only: [] do
      get 'payload', on: :member, to: 'boxes#payload'
    end
  end
  root to: 'visitors#index'
  get 'visitors/index'

  devise_for :users
  namespace :api do
    namespace :v1 do
      scope :decode do
        get 'datum/:box_id', to: 'data#decode'
      end
      resources :boxes, only: [:show] do
        resources :data, on: :member, only: [:create, :show, :update, :destroy, :update]
        get 'keys', on: :member, to: 'boxes#keys'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  before_create :set_jwt_key
  belongs_to :user
  has_secure_token
  attribute :public, :boolean, default: false
  has_many :data

  validates :jwt_key, write_once: true
  validates :title, presence: true

  def to_param
    token
  end

  def self.find(input)
    find_by_token(input)
  end

  def regenerate_jwt_key
    set_jwt_key
    save
  end

  def decode_jwt(jwt)
    JWT.decode(jwt, self.jwt_key, true, { algorithm: 'HS256' }).try(:first)
  end

  private

  def set_jwt_key
    self.jwt_key = SecureRandom.uuid
  end
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :box

  validates :identifier, uniqueness: {scope: :box_id}
  validates :identifier, presence: true
  validates :payload, presence: true
  #after_create :set_identifier
  #
  def as_jwt
    data = {identifier: identifier, payload: payload}
    JWT.encode(data, self.box.jwt_key, 'HS256')
  end

  private

  def set_identifier
    self.identifier = token
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :boxes
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::API
  include Pundit

end

app/controllers/api/v1/boxes_controller.rb
class Api::V1::BoxesController < Api::ApiController
  def show
    @box = Box.find params[:id]
    @data = @box.data.map { |d| {identifier: d.identifier, payload: d.payload} }
    #@data = @box.data.map { |d| {key: d.as_jwt } }
    render json: @data
  end

  def keys
    @box = Box.find params[:id]
    @data = @box.data.all.pluck(:identifier)
    render json: @data
  end
end

app/controllers/api/v1/data_controller.rb
class Api::V1::DataController < Api::ApiController # ~> NameError: uninitialized constant Api
  before_action :authenticate_user!, only: [:payload]
  def index
    set_box
    @data = @box.data.map{|d| [d.identifier, d.payload]}
    render json: { payload: @data }
  end
  def show
    set_box
    set_datum
    if @datum
      render json: {payload: @datum.payload, status: 'ok'}, status: '200'
    else
      render json: {status: 'not found'}, status: '404'
    end
  end

  def create
    check_if_json_format
    set_box
    data = JSON.parse(request.body.read)
    new_data = @box.data.new(identifier: data['identifier'],
                    payload: data['payload'],
                    host: request.host,
                    ip_address: request.remote_ip
                            )
    if @box.save
      render json: {msg: 'saved'}, status: 200
    else
      render json: {msg: 'error'}.merge(new_data.errors), status: 406
    end # => 
  end

  def destroy
    set_box
    set_datum
    if @datum.try(:destroy)
      render json: { msg: 'deleted' }, status: 200
    else
      render json: {msg: 'no such key'}, status: 406
    end
  end

  def update
    set_box
    set_datum
    @datum.payload = JSON.parse(request.body.read)['payload']
    if @datum.save
      render json: {msg: 'updated'}, status: 200
    else
      render json: {msg: 'oops'}
    end
  end

  def decode
    set_box
    authorize @box
    @data = @box.decode_jwt(params[:jwt])
    render json: @data
  end

  private

  def set_datum
    @datum = Datum.where(box: @box, identifier: params[:id]).first
  end

  def set_box
    @box = Box.find(params[:box_id])
  end

  def check_if_json_format
    return if request.format == 'application/json'
    #render nothing: true, status: 406
  end
end

# ~> NameError
# ~> uninitialized constant Api
# ~>
# ~> /var/folders/k3/q4dpz6p977q18bhrhq97gv6r0000gn/T/seeing_is_believing_temp_dir20171002-93235-1xx53ey/program.rb:1:in `<main>'

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
  include Pundit

  private

  def not_authorized
    render plain: 'Sorry, you cannot view this.'
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :payload]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = current_user.boxes.all
    authorize @boxes
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = current_user.boxes.new
    authorize @box
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = current_user.boxes.new(box_params)
    authorize @box

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payload
    @box = Box.find(params[:box_id])
    @datum = Datum.find_by_identifier(params[:id])
    authorize @datum
    #render json: @datum.payload
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
      authorize @box
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:title, :description, :public)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/api/v1/boxes_helper.rb
module Api::V1::BoxesHelper
end

app/helpers/api/v1/data_helper.rb
module Api::V1::DataHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/application/_javascript.html.slim
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
= yield(:javascript)

app/views/boxes/_form.html.slim
= simple_form_for(@box) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :public

  .form-actions
    = f.button :submit

app/views/boxes/edit.html.slim
h1 Editing box

== render 'form'

= link_to 'Show', @box
'  |
= link_to 'Back', boxes_path

app/views/boxes/index.html.slim
h1 Your DataBoxes

table.table.table-bordered.table-hover
  thead
    tr
      th Title
      th Description
      th Public
      th

  tbody
    - @boxes.each do |box|
      tr
        td = box.title
        td = box.description
        td = box.public
        td = link_to 'Show', box

br

= link_to 'New Box', new_box_path

app/views/boxes/new.html.slim
h1 New box

== render 'form'

= link_to 'Back', boxes_path

app/views/boxes/payload.html.slim
h1 Payload
#payloadeditor

- content_for(:javascript) do
  javascript:
    var container = document.getElementById('payloadeditor');
    var options = {};
    var editor = new JSONEditor(container, options);

    var json = #{raw(@datum.payload.to_json)};

    editor.set(json);

    var json = editor.get();
    editor.setMode('view');

app/views/boxes/show.html.slim
h1 = @box.title
p.lead = @box.description
hr
strong POST your JSON data to the following URL:
br
pre = api_v1_box_data_url(@box)
em JSON data should be in the format: <pre>{"identifier":"...", payload: ...}</pre>
hr
<strong>YOUR JWT KEY:</strong> <pre>#{@box.jwt_key}</pre>
hr
h2 Stored Data
table.table
  thead
    tr
      th Identifier
      th Payload
  tbody
    - @box.data.each do |datum|
      tr
        td = datum.identifier
        td = link_to "View Payload", payload_box_datum_path(@box, datum.identifier)

= link_to 'Back', boxes_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DataBox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  body[class="#{body_class}"]
    .container
      = yield
    = render 'javascript'

app/views/visitors/index.html.slim
h1 DataBoxes
p.lead This is a tiny web service that allows you to create api endpoints which
  accept json objects. You can then view the data online, or retrieve it through
  our API.
- if current_user
  .btn-group
    = link_to 'My Databoxes', boxes_path, class: 'btn btn-primary'
    = link_to 'Logout', destroy_user_session_path, method: :delete,
      class: 'btn btn-danger'
- else
  .btn-group
    = link_to "Register", new_user_registration_path, class: 'btn btn-success'
    = link_to "Login", new_user_session_path, class: 'btn btn-primary'